# Generated by Django 4.1.7 on 2023-03-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('role', models.CharField(max_length=16)),
                ('content', models.CharField(max_length=4096)),
            ],
        ),
    ]
